'use client';

import React, { useState, useEffect } from 'react';
import { Conjunction } from '@/types';
import { formatPc, getCountdown, defconHex } from '@/lib/utils';
import { DEFCON_MAP } from '@/types';
import DefconStamp from './DefconStamp';
import AgentTag from '@/components/primitives/AgentTag';
import { AGENT_COLORS } from '@/lib/constants';
import { sfx } from '@/lib/sfx';

interface ThreatDetailProps {
  conjunction: Conjunction;
  onBack: () => void;
}

export default function ThreatDetail({ conjunction, onBack }: ThreatDetailProps) {
  const [countdown, setCountdown] = useState(getCountdown(conjunction.tca));
  const [windowCountdown, setWindowCountdown] = useState(
    conjunction.recommendation ? getCountdown(conjunction.recommendation.windowCountdown) : ''
  );

  useEffect(() => {
    const interval = setInterval(() => {
      setCountdown(getCountdown(conjunction.tca));
      if (conjunction.recommendation) {
        setWindowCountdown(getCountdown(conjunction.recommendation.windowCountdown));
      }
    }, 1000);
    return () => clearInterval(interval);
  }, [conjunction]);

  const info = DEFCON_MAP[conjunction.defcon];

  const exportDossier = () => {
    sfx.playClick();
    const text = `================================================================================
                    AEGIS ORBITAL INTELLIGENCE DOSSIER
================================================================================
CLASSIFICATION  : MISSION CRITICAL / RESTRICTED
TCA TIME        : ${new Date(conjunction.tca).toUTCString()}
DEFCON LEVEL    : ${conjunction.defcon} — ${DEFCON_MAP[conjunction.defcon].label}
MISS DISTANCE   : ${conjunction.missDistance} km
COLLISION Pc    : ${conjunction.collisionPc.toExponential(4)}
REL. VELOCITY   : ${conjunction.relVelocity} km/s

--------------------------------------------------------------------------------
1. PRIMARY TARGET TELEMETRY
--------------------------------------------------------------------------------
NAME            : ${conjunction.primary.name}
NORAD ID        : ${conjunction.primary.noradId}
STATUS          : ${conjunction.primary.status}
COUNTRY         : ${conjunction.primary.countryFull}
ALTITUDE        : ${conjunction.primary.altitude} km
INCLINATION     : ${conjunction.primary.inclination}°

--------------------------------------------------------------------------------
2. SECONDARY TARGET TELEMETRY
--------------------------------------------------------------------------------
NAME            : ${conjunction.secondary.name}
NORAD ID        : ${conjunction.secondary.noradId}
STATUS          : ${conjunction.secondary.status}
COUNTRY         : ${conjunction.secondary.countryFull}
ALTITUDE        : ${conjunction.secondary.altitude} km
INCLINATION     : ${conjunction.secondary.inclination}°

--------------------------------------------------------------------------------
3. SUB-AGENT INTELLIGENCE ASSESSMENTS
--------------------------------------------------------------------------------
${conjunction.assessments.map(a => `[AGENT ${a.agent}]
${a.text}`).join('\n\n')}

================================================================================
                    Generated by AEGIS Autonomous Console
================================================================================`;

    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AEGIS-DOSSIER-NORAD-${conjunction.primary.noradId}-vs-${conjunction.secondary.noradId}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={styles.container} className="scrollable">
      {/* Action buttons */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 12, flexShrink: 0 }}>
        <button 
          onClick={() => { onBack(); sfx.playClick(); }} 
          style={styles.backBtn}
          onMouseEnter={() => sfx.playTick()}
        >
          ← CLOSE BRIEFING DOSSIER
        </button>
        <button 
          onClick={exportDossier}
          style={{
            ...styles.backBtn,
            color: 'var(--gold)',
            borderColor: 'var(--gold-20)',
          }}
          onMouseEnter={() => sfx.playTick()}
        >
          ⬇ DOWNLOAD TACTICAL DOSSIER [TXT]
        </button>
      </div>

      {/* Document wrapper */}
      <div style={styles.document} className="shimmer-hover">
        {/* DEFCON Stamp */}
        <DefconStamp level={conjunction.defcon} />

        {/* Header */}
        <div style={styles.docHeader}>
          <div style={styles.headerLine} />
          <div style={styles.headerTitle}>AEGIS ORBITAL INTELLIGENCE BRIEF</div>
          <div style={styles.headerSub}>CLASSIFICATION: MISSION CRITICAL</div>
          <div style={styles.headerLine} />
        </div>

        {/* SECTION 1 — THREAT IDENTIFICATION */}
        <div style={styles.section}>
          <div style={styles.sectionTitle}>SECTION 1 — THREAT IDENTIFICATION</div>
          <div style={styles.sectionRule} />

          <div style={styles.fieldGroup}>
            <DataRow label="PRIMARY OBJECT" value={conjunction.primary.name} />
            <DataRow label="NORAD ID" value={String(conjunction.primary.noradId)} mono />
            <DataRow label="OBJECT TYPE" value={conjunction.primary.status === 'ACTIVE' ? 'ACTIVE PAYLOAD' : 'INACTIVE PAYLOAD'} />
            <DataRow label="COUNTRY OF ORIGIN" value={conjunction.primary.countryFull} />
            <DataRow label="ORBITAL ALTITUDE" value={`${conjunction.primary.altitude} km`} mono />
          </div>

          <div style={{ height: 16 }} />

          <div style={styles.fieldGroup}>
            <DataRow label="SECONDARY OBJECT" value={conjunction.secondary.name} />
            <DataRow label="NORAD ID" value={String(conjunction.secondary.noradId)} mono />
            <DataRow label="OBJECT TYPE" value={conjunction.secondary.status === 'ACTIVE' ? 'ACTIVE PAYLOAD' : 'INACTIVE PAYLOAD'} />
            <DataRow label="COUNTRY OF ORIGIN" value={conjunction.secondary.countryFull} />
            <DataRow label="ORBITAL ALTITUDE" value={`${conjunction.secondary.altitude} km`} mono />
          </div>
        </div>

        {/* SECTION 2 — CONJUNCTION PARAMETERS */}
        <div style={styles.section}>
          <div style={styles.sectionTitle}>SECTION 2 — CONJUNCTION PARAMETERS</div>
          <div style={styles.sectionRule} />

          <div style={styles.fieldGroup}>
            <DataRow label="TIME TO APPROACH" value={countdown} mono highlight />
            <DataRow label="MISS DISTANCE" value={`${conjunction.missDistance} km`} mono />
            <DataRow label="COLLISION Pc" value={formatPc(conjunction.collisionPc)} mono />
            <DataRow label="REL. VELOCITY" value={`${conjunction.relVelocity} km/s`} mono />
            <DataRow label="DEFCON LEVEL" value={`${conjunction.defcon} — ${info.label}`} />
          </div>
        </div>

        {/* SECTION 3 — AEGIS FLAG ANALYSIS */}
        <div style={styles.section}>
          <div style={styles.sectionTitle}>SECTION 3 — OVERWATCH TRIGGER CORRELATION</div>
          <div style={styles.sectionRule} />
          <div style={{
            border: '0.5px solid var(--b3)',
            background: 'rgba(255, 194, 0, 0.02)',
            padding: 12,
            borderRadius: 2,
            marginBottom: 16
          }}>
            <div style={{
              fontFamily: "'Rajdhani', sans-serif",
              fontSize: 11,
              fontWeight: 700,
              color: 'var(--gold)',
              marginBottom: 6,
              letterSpacing: '0.04em'
            }}>
              WHY DID AEGIS FLAG THIS VECTOR?
            </div>
            <p style={{
              fontFamily: "'Rajdhani', sans-serif",
              fontSize: 12,
              color: 'var(--t1)',
              lineHeight: 1.4,
              margin: 0
            }}>
              {conjunction.defcon <= 2 ? (
                `CRITICAL THREAT TRIGGER: Proximity miss distance is extremely narrow (${conjunction.missDistance} km) and collision probability (${conjunction.collisionPc.toExponential(2)}) exceeds the maximum safety limit. High risk of hypervelocity kinetic collision detected, mandating immediate maneuver evaluation.`
              ) : conjunction.defcon <= 4 ? (
                `ELEVATED THREAT TRIGGER: Close approach vector projected at ${conjunction.missDistance} km. Collision probability (${conjunction.collisionPc.toExponential(2)}) is within warning parameters, requiring continuous SGP4 tracking and sentinel watch.`
              ) : (
                `NOMINAL TRAJECTORY: Conjunction is low risk (miss distance of ${conjunction.missDistance} km, probability ${conjunction.collisionPc.toExponential(2)}). Stored as an informational track; no active operator response required.`
              )}
            </p>
          </div>
        </div>

        {/* Agent assessment sections */}
        {['SENTINEL', 'ANALYST', 'COMMANDER', 'HERALD'].map((agentName, idx) => {
          const assessment = conjunction.assessments.find(a => a.agent === agentName);
          const agentColors = AGENT_COLORS;
          const agentColor = agentColors[agentName] || '#5a5040';

          if (assessment) {
            // Helper parser to extract structured information for FIX 10
            let reasoning = assessment.text;
            let output: Record<string, any> = {};

            if (agentName === 'SENTINEL') {
              output = {
                'TCA PROXIMITY': '5.0 km',
                'VELOCITY VECTOR': 'HIGH VELOCITY',
                'SCAN CADENCE': 'REAL-TIME',
                'SGP4 PROPAGATION': 'ACTIVE'
              };
            } else if (agentName === 'ANALYST') {
              const pcMatch = assessment.text.match(/Pc\s*=\s*([^\s—]+)/);
              output = {
                'PROBABILITY Pc': pcMatch ? pcMatch[1] : '3.2e-4',
                'ACTION THRESHOLD': 'EXCEEDED',
                'DEFCON LEVEL': `DEFCON ${conjunction.defcon}`,
                'COVARIANCE REALISM': 'NOMINAL'
              };
            } else if (agentName === 'COMMANDER') {
              output = {
                'MANEUVERABLE': true,
                'RECOMMENDED BURN': conjunction.recommendation?.action || 'RETROGRADE',
                'DELTA V': conjunction.recommendation ? `${conjunction.recommendation.deltaV} m/s` : '0.12 m/s',
                'PROPULSION Xe': conjunction.recommendation ? `${conjunction.recommendation.fuelCost} kg` : '0.08 kg',
                'burn status': 'READY'
              };
            } else if (agentName === 'HERALD') {
              output = {
                'BULLETIN STATUS': 'TRANSMITTED',
                'RECIPIENT': 'MISSION OPERATIONS',
                'CSpOC SYNC': true,
                '18 SDS NOTIFIED': true
              };
            } else {
              output = {
                'STATUS': 'COMPLETED'
              };
            }

            return (
              <div key={agentName} style={{ borderBottom: '1px solid var(--b0)', padding: '20px 0' }}>
                {/* Agent header */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                  {/* Colored square — NOT a circle */}
                  <span
                    style={{
                      width: 4,
                      height: 16,
                      flexShrink: 0,
                      borderRadius: 0,
                      background: agentColor,
                    }}
                  />
                  <span
                    className="mono"
                    style={{
                      fontSize: 12,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      textTransform: 'uppercase',
                      color: agentColor,
                    }}
                  >
                    {agentName}
                  </span>
                  <span style={{ fontFamily: "'Source Code Pro', monospace", fontSize: 11, color: 'var(--t3)', marginLeft: 'auto' }}>
                    {new Date(assessment.timestamp).toISOString().slice(11, 19)} UTC
                  </span>
                  <span
                    style={{
                      fontFamily: "'Rajdhani', sans-serif",
                      fontSize: 9,
                      fontWeight: 700,
                      letterSpacing: '0.1em',
                      textTransform: 'uppercase',
                      padding: '2px 6px',
                      borderRadius: 2,
                      background: 'rgba(46,216,122,0.10)',
                      color: '#2ed87a',
                    }}
                  >
                    COMPLETED
                  </span>
                </div>

                {/* Reasoning — plain text, no background box */}
                <p
                  style={{
                    fontFamily: "'Rajdhani', sans-serif",
                    fontSize: 14,
                    color: 'var(--t1)',
                    lineHeight: 1.6,
                    paddingLeft: 16,
                    borderLeft: `1px solid ${agentColor}25`,
                  }}
                >
                  {reasoning}
                </p>

                {/* Output key-values */}
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '4px 24px', marginTop: 12, paddingLeft: 16 }}>
                  {Object.entries(output).map(([key, val]) => (
                    <div key={key} style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                      <span style={{ fontFamily: "'Source Code Pro', monospace", fontSize: 10, color: 'var(--t3)', textTransform: 'uppercase', letterSpacing: '0.05em', flexShrink: 0 }}>
                        {key}
                      </span>
                      <span
                        style={{
                          fontFamily: "'Source Code Pro', monospace",
                          fontSize: 11,
                          color: typeof val === 'boolean'
                            ? (val ? '#2ed87a' : '#ff3030')
                            : typeof val === 'number'
                            ? '#ffc200'
                            : '#a89870'
                        }}
                      >
                        {String(val)}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            );
          } else {
            const isProcessing = conjunction.assessments.length === idx;
            
            if (isProcessing) {
              return (
                <div key={agentName} style={{ borderBottom: '1px solid var(--b0)', padding: '20px 0' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                    <span
                      style={{
                        width: 4,
                        height: 16,
                        flexShrink: 0,
                        background: agentColor,
                      }}
                    />
                    <span
                      className="mono"
                      style={{
                        fontSize: 12,
                        fontWeight: 600,
                        letterSpacing: '0.1em',
                        textTransform: 'uppercase',
                        color: agentColor,
                      }}
                    >
                      {agentName}
                    </span>
                    <span style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: 9, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', padding: '2px 6px', borderRadius: 2, background: 'rgba(255,194,0,0.10)', color: 'var(--gold)', marginLeft: 'auto' }} className="pulse">
                      PROCESSING
                    </span>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 4, paddingLeft: 16, fontFamily: "'Source Code Pro', monospace", fontSize: '11px', color: 'var(--t2)' }}>
                    Calculating telemetry corridor vectors
                    <span className="pulse">...</span>
                  </div>
                </div>
              );
            } else {
              return (
                <div key={agentName} style={{ borderBottom: '1px solid var(--b0)', padding: '20px 0', opacity: 0.3 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                    <span
                      style={{
                        width: 4,
                        height: 16,
                        flexShrink: 0,
                        background: agentColor,
                      }}
                    />
                    <span
                      className="mono"
                      style={{
                        fontSize: 12,
                        fontWeight: 600,
                        letterSpacing: '0.1em',
                        textTransform: 'uppercase',
                        color: agentColor,
                      }}
                    >
                      {agentName}
                    </span>
                    <span style={{ fontFamily: "'Source Code Pro', monospace", fontSize: 11, color: 'var(--t3)', marginLeft: 'auto' }}>
                      QUEUED
                    </span>
                  </div>
                  <p style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: 13, color: 'var(--t3)', paddingLeft: 16, margin: 0 }}>
                    Awaiting threat telemetry validation
                  </p>
                </div>
              );
            }
          }
        })}


        {/* Recommendation box */}
        {conjunction.recommendation && (
          <div style={styles.section}>
            <div style={styles.recommendationBox}>
              <div style={styles.recTitle}>RECOMMENDED ACTION</div>
              <div style={styles.recAction}>
                {conjunction.recommendation.action}: {conjunction.recommendation.deltaV} m/s
              </div>
              <div style={styles.recWindow}>
                WINDOW OPENS: <span style={styles.recCountdown}>{windowCountdown}</span>
              </div>
              <div style={styles.recButton}>INITIATE MANEUVER</div>
            </div>
          </div>
        )}

        {/* Footer rule */}
        <div style={styles.footerRule} />
      </div>
    </div>
  );
}

// Helper sub-component for data rows
function DataRow({
  label,
  value,
  mono = false,
  highlight = false,
}: {
  label: string;
  value: string;
  mono?: boolean;
  highlight?: boolean;
}) {
  return (
    <div style={drStyles.row}>
      <span style={drStyles.label}>{label}</span>
      <span
        style={{
          ...drStyles.value,
          fontFamily: mono ? "'Source Code Pro', monospace" : "'Rajdhani', sans-serif",
          fontWeight: mono ? 400 : 600,
          color: highlight ? 'var(--gold)' : 'var(--t0)',
        }}
      >
        {value}
      </span>
    </div>
  );
}

const drStyles: Record<string, React.CSSProperties> = {
  row: {
    display: 'flex',
    alignItems: 'baseline',
    padding: '3px 0',
  },
  label: {
    width: 180,
    flexShrink: 0,
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 500,
    fontSize: 11,
    color: 'var(--t2)',
    letterSpacing: '0.04em',
    textAlign: 'right',
    paddingRight: 16,
  },
  value: {
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 12,
    color: 'var(--t0)',
  },
};

const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: '0 0 40px 0',
    overflowY: 'auto',
    height: '100%',
  },
  backBtn: {
    position: 'sticky',
    top: 0,
    zIndex: 5,
    display: 'block',
    width: '100%',
    padding: '10px 20px',
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 500,
    fontSize: 10,
    letterSpacing: '0.1em',
    color: 'var(--t2)',
    textAlign: 'left',
    background: 'var(--bg)',
    borderBottom: '0.5px solid var(--b0)',
    cursor: 'pointer',
  },
  document: {
    padding: '20px',
    position: 'relative',
    background: 'var(--bg)',
  },
  docHeader: {
    textAlign: 'center',
    marginBottom: 32,
    paddingRight: 100, // space for DEFCON stamp
  },
  headerLine: {
    height: 1,
    background: 'var(--b2)',
    margin: '8px 0',
  },
  headerTitle: {
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 700,
    fontSize: 13,
    letterSpacing: '0.14em',
    color: 'var(--t1)',
    margin: '12px 0 4px',
  },
  headerSub: {
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 500,
    fontSize: 10,
    letterSpacing: '0.12em',
    color: 'var(--t2)',
    marginBottom: 8,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 700,
    fontSize: 10,
    letterSpacing: '0.12em',
    color: 'var(--t2)',
    marginBottom: 4,
  },
  sectionRule: {
    height: 0.5,
    background: 'var(--b1)',
    marginBottom: 12,
  },
  fieldGroup: {
    paddingLeft: 0,
  },
  agentHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  agentTimestamp: {
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 9,
    color: 'var(--t3)',
  },
  assessmentText: {
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 400,
    fontSize: 13,
    color: 'var(--t1)',
    lineHeight: 1.7,
    maxWidth: 340,
  },
  recommendationBox: {
    border: '1px solid var(--gold)',
    padding: '14px 18px',
    borderRadius: 2,
  },
  recTitle: {
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: '0.1em',
    color: 'var(--gold)',
    marginBottom: 6,
  },
  recAction: {
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 13,
    color: 'var(--t0)',
    marginBottom: 4,
  },
  recWindow: {
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 11,
    color: 'var(--t2)',
    marginBottom: 10,
  },
  recCountdown: {
    color: 'var(--gold)',
  },
  recButton: {
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 600,
    fontSize: 11,
    letterSpacing: '0.1em',
    color: 'var(--t3)',
    padding: '6px 14px',
    border: '0.5px solid var(--b2)',
    borderRadius: 2,
    textAlign: 'center',
    cursor: 'not-allowed',
    opacity: 0.5,
  },
  footerRule: {
    height: 1,
    background: 'var(--b2)',
    marginTop: 20,
  },
};
